
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 26;
  public static final int MENOS = 12;
  public static final int DOSPUNTOS = 24;
  public static final int CADENA = 2;
  public static final int INT = 7;
  public static final int CHAR = 5;
  public static final int FINCADENA = 9;
  public static final int DECIMAL = 4;
  public static final int IMPRIMIR = 10;
  public static final int AT = 21;
  public static final int ID = 6;
  public static final int TABLE = 27;
  public static final int COMA = 23;
  public static final int STRING = 8;
  public static final int EOF = 0;
  public static final int MULT = 13;
  public static final int DATABASE = 20;
  public static final int DIV = 14;
  public static final int ADD = 25;
  public static final int LLAVE2 = 18;
  public static final int error = 1;
  public static final int PAR2 = 16;
  public static final int LLAVE1 = 17;
  public static final int PAR1 = 15;
  public static final int USE = 19;
  public static final int ENTERO = 3;
  public static final int STORE = 22;
  public static final int MAS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "CHAR",
  "ID",
  "INT",
  "STRING",
  "FINCADENA",
  "IMPRIMIR",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "PAR1",
  "PAR2",
  "LLAVE1",
  "LLAVE2",
  "USE",
  "DATABASE",
  "AT",
  "STORE",
  "COMA",
  "DOSPUNTOS",
  "ADD",
  "READ",
  "TABLE"
  };
}

