
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 10;
  public static final int CADENA = 2;
  public static final int CHAR = 5;
  public static final int FINCADENA = 7;
  public static final int DECIMAL = 4;
  public static final int IMPRIMIR = 8;
  public static final int AT = 19;
  public static final int ID = 6;
  public static final int EOF = 0;
  public static final int MULT = 11;
  public static final int DATABASE = 18;
  public static final int DIV = 12;
  public static final int error = 1;
  public static final int PAR2 = 14;
  public static final int LLAVE2 = 16;
  public static final int PAR1 = 13;
  public static final int LLAVE1 = 15;
  public static final int USE = 17;
  public static final int ENTERO = 3;
  public static final int STORE = 20;
  public static final int MAS = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "CHAR",
  "ID",
  "FINCADENA",
  "IMPRIMIR",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "PAR1",
  "PAR2",
  "LLAVE1",
  "LLAVE2",
  "USE",
  "DATABASE",
  "AT",
  "STORE"
  };
}

